CREATE TABLE asset_balances (
    id UUID NOT NULL,
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    asset_key VARCHAR(191) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    asset_name VARCHAR(100),
    asset_category VARCHAR(20) NOT NULL,
    network VARCHAR(50),
    asset_ref VARCHAR(255),
    total_quantity NUMERIC(38, 18) NOT NULL,
    available_quantity NUMERIC(38, 18),
    locked_quantity NUMERIC(38, 18),
    unit_price NUMERIC(38, 18),
    price_currency VARCHAR(8),
    price_source VARCHAR(50),
    price_evaluated_at TIMESTAMPTZ,
    fx_rate_to_jpy NUMERIC(24, 12),
    fx_source VARCHAR(50),
    fx_evaluated_at TIMESTAMPTZ,
    jpy_value NUMERIC(38, 8),
    valuation_status VARCHAR(20) NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    last_success_sync_run_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_asset_balances PRIMARY KEY (id),
    CONSTRAINT uq_asset_balances_connection_asset UNIQUE (connection_id, user_id, asset_key),
    CONSTRAINT fk_asset_balances_connection FOREIGN KEY (connection_id, user_id)
        REFERENCES connections (id, user_id),
    CONSTRAINT fk_asset_balances_last_run FOREIGN KEY (last_success_sync_run_id, connection_id, user_id)
        REFERENCES sync_runs (id, connection_id, user_id),
    CONSTRAINT ck_asset_balances_category CHECK (asset_category IN ('CRYPTO', 'STABLECOIN', 'FIAT')),
    CONSTRAINT ck_asset_balances_quantity CHECK (total_quantity >= 0),
    CONSTRAINT ck_asset_balances_valuation_status CHECK (valuation_status IN ('VALUED', 'UNAVAILABLE')),
    CONSTRAINT ck_asset_balances_fx_rate CHECK (fx_rate_to_jpy IS NULL OR fx_rate_to_jpy > 0)
);

CREATE TABLE perpetual_positions (
    id UUID NOT NULL,
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    position_key VARCHAR(191) NOT NULL,
    instrument_code VARCHAR(50) NOT NULL,
    side VARCHAR(10) NOT NULL,
    quantity NUMERIC(38, 18) NOT NULL,
    entry_price NUMERIC(38, 18),
    mark_price NUMERIC(38, 18),
    liquidation_price NUMERIC(38, 18),
    price_currency VARCHAR(8) NOT NULL,
    leverage NUMERIC(18, 8),
    margin_amount NUMERIC(38, 18),
    margin_currency VARCHAR(8),
    unrealized_pnl NUMERIC(38, 18),
    pnl_currency VARCHAR(8),
    price_fx_rate_to_jpy NUMERIC(24, 12),
    price_fx_source VARCHAR(50),
    price_fx_evaluated_at TIMESTAMPTZ,
    margin_fx_rate_to_jpy NUMERIC(24, 12),
    margin_fx_source VARCHAR(50),
    margin_fx_evaluated_at TIMESTAMPTZ,
    pnl_fx_rate_to_jpy NUMERIC(24, 12),
    pnl_fx_source VARCHAR(50),
    pnl_fx_evaluated_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL,
    last_success_sync_run_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_perpetual_positions PRIMARY KEY (id),
    CONSTRAINT uq_perpetual_positions_connection_position UNIQUE (connection_id, user_id, position_key),
    CONSTRAINT fk_perpetual_positions_connection FOREIGN KEY (connection_id, user_id)
        REFERENCES connections (id, user_id),
    CONSTRAINT fk_perpetual_positions_last_run FOREIGN KEY (last_success_sync_run_id, connection_id, user_id)
        REFERENCES sync_runs (id, connection_id, user_id),
    CONSTRAINT ck_perpetual_positions_side CHECK (side IN ('LONG', 'SHORT')),
    CONSTRAINT ck_perpetual_positions_quantity CHECK (quantity > 0),
    CONSTRAINT ck_perpetual_positions_leverage CHECK (leverage IS NULL OR leverage > 0),
    CONSTRAINT ck_perpetual_positions_margin CHECK (margin_amount IS NULL OR margin_amount >= 0),
    CONSTRAINT ck_perpetual_positions_price_fx CHECK (price_fx_rate_to_jpy IS NULL OR price_fx_rate_to_jpy > 0),
    CONSTRAINT ck_perpetual_positions_margin_fx CHECK (margin_fx_rate_to_jpy IS NULL OR margin_fx_rate_to_jpy > 0),
    CONSTRAINT ck_perpetual_positions_pnl_fx CHECK (pnl_fx_rate_to_jpy IS NULL OR pnl_fx_rate_to_jpy > 0)
);

CREATE TABLE provider_account_states (
    id UUID NOT NULL,
    connection_id UUID NOT NULL,
    user_id UUID NOT NULL,
    account_currency VARCHAR(8),
    cash_balance NUMERIC(38, 18),
    collateral_balance NUMERIC(38, 18),
    account_equity NUMERIC(38, 18),
    unrealized_pnl NUMERIC(38, 18),
    equity_includes_unrealized_pnl BOOLEAN,
    fx_rate_to_jpy NUMERIC(24, 12),
    fx_source VARCHAR(50),
    fx_evaluated_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL,
    last_success_sync_run_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_provider_account_states PRIMARY KEY (id),
    CONSTRAINT uq_provider_account_states_connection UNIQUE (connection_id, user_id),
    CONSTRAINT fk_provider_account_states_connection FOREIGN KEY (connection_id, user_id)
        REFERENCES connections (id, user_id),
    CONSTRAINT fk_provider_account_states_last_run FOREIGN KEY (last_success_sync_run_id, connection_id, user_id)
        REFERENCES sync_runs (id, connection_id, user_id),
    CONSTRAINT ck_provider_account_states_fx_rate CHECK (fx_rate_to_jpy IS NULL OR fx_rate_to_jpy > 0)
);
